# Generated by Django 5.1.3 on 2025-02-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_categories_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='Categories',
        ),
    ]
