# Generated by Django 5.1.6 on 2025-02-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_item_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='discount_total_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='total_price',
        ),
    ]
