# Generated by Django 5.1.3 on 2025-02-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_product_discount_price_product_discount_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='members_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
