# Generated by Django 5.1.6 on 2025-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_remove_item_discount_remove_item_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
