# Generated by Django 5.1.3 on 2025-02-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_purchase_discount_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupdeposit',
            name='compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='compunding_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='daily_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='monthly_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='product_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='compunding_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='daily_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='monthly_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='product_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
