# Generated by Django 5.1.3 on 2025-02-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_product_members_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='membership_status',
            field=models.BooleanField(default=False),
        ),
    ]
