# Generated by Django 5.1.3 on 2025-02-27 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_cashupdeposit_compounding_profit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashupdeposit',
            old_name='compunding_withdraw',
            new_name='compounding_withdraw',
        ),
    ]
