# Generated by Django 5.1.3 on 2025-02-25 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_remove_item_price_cashupowingdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='compounding_withdraw',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='CashupDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashup_main_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compounding_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_compounding_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_compounding_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('withdraw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compounding_withdraw', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashup_deposit', to='myapi.buyer')),
            ],
        ),
    ]
