# Generated by Django 5.1.3 on 2025-02-27 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_rename_compunding_withdraw_cashupowingdeposit_compounding_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BuyerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.buyer')),
            ],
        ),
    ]
