# Generated by Django 5.1.3 on 2025-02-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_cashupowingdeposit_compounding_withdraw_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
