# Generated by Django 5.1.3 on 2025-02-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0011_purchase_paid_buyertransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='membership_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
