# Generated by Django 5.1.3 on 2025-02-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_purchase_membership_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='members_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
