# Generated by Django 5.1.3 on 2025-02-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_item_members_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='buyer_image',
            field=models.ImageField(blank=True, help_text='Image of the buyer', null=True, upload_to='item_images/'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, help_text='Image of the product', null=True, upload_to='item_images/'),
        ),
    ]
