# Generated by Django 5.1.3 on 2025-02-28 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_buyer_buyer_image_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='discount_price',
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='daily_compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='monthly_compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='daily_compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='monthly_compounding_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
