# Generated by Django 5.1.3 on 2025-02-26 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_alter_buyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='compounding_withdraw',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='daily_compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='daily_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='monthly_compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='monthly_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='product_profit',
        ),
        migrations.RemoveField(
            model_name='cashupdeposit',
            name='withdraw',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='compounding_withdraw',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='daily_compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='daily_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='monthly_compounding_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='monthly_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='product_profit',
        ),
        migrations.RemoveField(
            model_name='cashupowingdeposit',
            name='withdraw',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='members_price',
        ),
        migrations.AddField(
            model_name='buyer',
            name='main_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cashupdeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cashupowingdeposit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='myapi.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashupdeposit',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashup_deposits', to='myapi.buyer'),
        ),
        migrations.AlterField(
            model_name='cashupowingdeposit',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashup_owing_deposits', to='myapi.buyer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
