# Generated by Django 5.1.3 on 2025-02-26 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_remove_cashupdeposit_compounding_profit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='discount_rate',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='original_price',
        ),
        migrations.AddField(
            model_name='purchase',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='myapi.buyer'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
