# Generated by Django 5.1.3 on 2025-03-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_buyertransaction_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyertransaction',
            name='method',
            field=models.CharField(choices=[('B', 'BKash'), ('N', 'Nagad')], default='B', max_length=1),
        ),
    ]
