# Generated by Django 5.1.3 on 2025-02-26 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_remove_purchase_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='discount_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
