# Generated by Django 5.1.3 on 2025-02-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_alter_purchase_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='address',
        ),
        migrations.AddField(
            model_name='buyer',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
