# Generated by Django 5.1.3 on 2025-02-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_remove_buyer_address_buyer_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
